#! /bin/bash

# go to root directory
cd "$(dirname "$0")"

# PRE-CONDITION
#	https://github.com/julienXX/terminal-notifier -> ONLY MAC 10.9+
#		install by `brew install terminal-notifier` if your mac has Homebrew installed
# CREATE_SCRIPT_BY Kamontat Chantrachirathumrong

# To watch background running `ps -T`
# To kill only 1 task/jobs `kill <PID>` (PID = you can find that in command `ps -T`)
# To remove all background `pkill -f <FILE_NAME>` (FILE_NAME = file that run background process)

# -------------------------- IMPORT SECTION --------------------------

. ./variable

# -------------------------- FUNCTION SECTION --------------------------

# exit bg job
function ctrl_c {
    echo ""
	echo "ctrl+c occurred"
	pkill -f background
}

function clean_temp_file {
	rm -f $VAR_FILE
	rm -f $HOMEBREW_RUBY_FILE
}

# -------------------------- CODE SECTION --------------------------

# Exception if user exit program by ctrl+c/command+c
trap ctrl_c SIGINT

# check first params
if [ "${1:-}" ]; then 
	echo "have params"
else 
	echo "no params"
fi

./script/installation

./script/background
./script/foraground

clean_temp_file

# ------------------------- END CODE SECTION -------------------------