#! /bin/bash

# --------------------------- IMPORT SECTION ---------------------------

. ./variable/config_var

# -------------------------- FUNCTION SECTION --------------------------

function download_file_var {
	arr=($(<$VAR_FILE))
	if [[ ${arr[*]} != "" ]]; then 
		second=${arr[0]}
		label=${arr[1]}
		timeout=${arr[2]}
	fi
}

function show {
	echo ""
	download_file_var
	echo "Current time: $second second(s), All time: $SECONDS"
	echo "Alert timer: $label, Alert_timeout: $timeout"
}

function exit {
	echo ""
	pkill -f background
}

function no_command {
	echo "no command"
}

function input {
	while true; do
		read -n1 -p "show[s], exit[e] > " doit 
		case $doit in
			s|S) show ;;
			e|E) exit && break ;;
			*) no_command ;; 
		esac
	done
}

# -------------------------- CODE SECTION --------------------------

input

# ------------------------- END CODE SECTION -------------------------