#!/bin/bash

# --------------------------- IMPORT SECTION ---------------------------

. ./variable/constant_var

# -------------------------- VARIABLE SECTION --------------------------

homebrew="brew"
homebrew_install_command="/usr/bin/ruby $HOMEBREW_RUBY_FILE"

terminal_notifier="terminal-notifier"
terminal_notifier_install_command="brew terminal-notifier"

# -------------------------- FUNCTION SECTION --------------------------

function is_exist {
  	if ! local r="$(type -p "$1")" || [ -z "$r" ]; then
    	echo $FALSE
  	else 
    	echo $TRUE
  	fi
}

function check_install {
  	if [ "$(is_exist "$1")" == $FALSE ]; then
		echo "$1 not exist!"
    	echo "try to installed."
    	$2
	else
		echo "$1 exist!"
  	fi
}

function load_homebrew_rb {
	curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install > $HOMEBREW_RUBY_FILE
}

# -------------------------- CODE SECTION --------------------------

load_homebrew_rb

check_install "$homebrew" "$homebrew_install_command"
check_install "$terminal_notifier" "$terminal_notifier_install_command"

rm -f $HOMEBREW_RUBY_FILE

# ------------------------- END CODE SECTION -------------------------